### PR TITLE
Feat/dw/add tests

### PR DESCRIPTION
**Pull request by danwagnerco**
This PR implements two big changes but leaves almost all of the existing API intact.
- Adds rpsec tests to all public methods
- Uses [`bundler`](http://bundler.io/) and the `dtvcontroller.gemspec` to manage all dependencies

Methods `get_channel`, `send_key`, `tune` and `get_sysinfo` all still work like gangbusters, and you can run full test suite by simply executing `rake` at the command line.

The major differences:
- Timeout-handling. This implementation raises a `RuntimeError` with message "Cannot connect to set top box" when an `Errno::ETIMEDOUT` is caught, and raises a similar `RuntimeError` with message "Unreachable host likely caused by no internet connect" when an `Errno::EHOSTUNREACH` is caught
- Validation on input to the `get_sysinfo` and `system_info` methods. If the user tries to pass in something that is NOT on the short list of acceptable system info options (stored in the hash `SYSTEM_INFO_HASH`), a `RuntimeError` is raised with message "Unrecognized system option: {name_of_the_bad_input_here}".
- Validation on input to the `send_key` method. When a user tries to path in a key that is NOT on the list of acceptable remote key options (stored in the array `SEND_KEY_OPTIONS`), a `RuntimeError` is raised with message "Unknown remote key: {name_of_the_bad_input_here}".

### CODE REVIEW

**Comment by nickpetty** [comment]
Thanks for the update!  Haven't touched ruby in a while, but good to see someone is using the gem!

**Comment by danwagnerco** [comment]
Was a fun project to work on :+1: and, if you can believe it, helped solve a real problem!

**Comment by nickpetty** [comment]
That's what I built for as well!  What are you implementing it in if I may ask?

**Comment by danwagnerco** [comment]
Here's the scoop -- I have a dog, and like most dogs, he'll occasionally bark at a noise during the day. (Our neighbors work from home and DEMAND quiet.) 

To keep my little dude distracted, I like to leave the TV on while I'm at the office -- a little local noise goes a long way to keep his mind off passing fire trucks, neighbors talking in the hallway, etc. Unfortunately, some days I would come home and see that my DirecTV was bouncing around a screen saver, argh!

After a [handful](http://forums.directv.com/thread/11252191) of [searches](http://www.avsforum.com/forum/36-home-v-distribution/1523021-there-way-disable-directv-screensaver-automated-macro-remote-laptop.html), I learned about the apparently un-disable-able screensaver, the low-tech "just hit the dash key" solution and the SHEF API. From there, it only took a few visits to Rubygems and Github to find your gem!

**Comment by nickpetty** [comment]
That's an awesome idea!  Glad I was able to help!  I created it to control a box at a casino I was working at.  Before, we would have to drive from our office to the casino, go up three flights of stairs, and change the channel.  This allowed us to just do it from the office when we got a call.  Anywho, thanks for cleaning it up, it was my first gem!

**Comment by danwagnerco** [comment]
Love it -- solving real problems makes programming fun. And the gem didn't need much cleanup, it was already doing great work!

**Pull request merged**
